changes for version rollback

diff --git a/.github/workflows/reusable-lambda-deployment.yml b/.github/workflows/reusable-lambda-deployment.yml
--- a/.github/workflows/reusable-lambda-deployment.yml
+++ b/.github/workflows/reusable-lambda-deployment.yml
@@ -15,6 +15,10 @@ on:
         description: 'Dynamically generated tag, format curdate_curtime'
         required: true
         type: string
+      health_endpoint:
+        description: 'endpoint to check the health of the server'
+        required: true
+        type: string
 
     secrets:
       AWS_REGION:
@@ -53,3 +57,27 @@ jobs:
             --region ${{ secrets.AWS_REGION }} \
             --function-name ${{ inputs.app_lambda_function_name }} \
             --image-uri $IMAGE_URI
+
+      - name: Publish New Version of Lambda Function
+        run: |
+            aws lambda wait function-updated --function-name ${{ inputs.app_lambda_function_name }}
+            aws lambda publish-version --function-name ${{ inputs.app_lambda_function_name }}
+
+      - name: Test /health endpoint
+        id: test
+        run: |
+          # Test the /health endpoint
+          curl --fail ${{ inputs.health_endpoint }} || exit 1
+
+      - name: Rollback if needed
+#        if: failure()  # Run this step only if previous steps failed
+        run: |
+          # Rollback to the previous Lambda version using alias
+          PREV_VERSION=$(aws lambda list-versions-by-function
+                        --region ${{ secrets.AWS_REGION }} \
+                        --function-name ${{ inputs.app_lambda_function_name }} \
+                        --query 'Versions[-2].Version' --output text)
+          aws lambda update-alias \
+          --region ${{ secrets.AWS_REGION }} \
+          --function-name ${{ inputs.app_lambda_function_name }} \
+          --name live --function-version $PREV_VERSION
